version: "3.9"

services:
  # ------------------- User DB -------------------
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: users
    ports:
      - "5433:5432"  # host:container
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - microservices-net

  # ------------------- Task DB -------------------
  task-db:
    image: postgres:15
    container_name: task-db
    environment:
      POSTGRES_USER: mytask
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tasks
    ports:
      - "5434:5432"
    volumes:
      - task-db-data:/var/lib/postgresql/data
    networks:
      - microservices-net

  # ------------------- User Service -------------------
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://myuser:mypassword@user-db:5432/users
    depends_on:
      - user-db
    networks:
      - microservices-net

  # ------------------- Task Service -------------------
  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://myuser:mypassword@task-db:5432/tasks
    depends_on:
      - task-db
    networks:
      - microservices-net

  # ------------------- Gateway Service -------------------
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1
      - USER_SERVICE_URL=http://user-service:8000
      - TASK_SERVICE_URL=http://task-service:8001
    depends_on:
      - user-service
      - task-service
    networks:
      - microservices-net

  # ------------------- Nginx (Optional) -------------------
  local-nginx:
    image: nginx:latest
    container_name: local-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - gateway-service
    networks:
      - microservices-net

volumes:
  user-db-data:
  task-db-data:

networks:
  microservices-net:
    driver: bridge
